// lib/uploadData.ts
import { collection, addDoc } from "firebase/firestore";
import { db } from "./firebase"; // Adjust the path as needed

const openMicData = [
    {
      "name": "Punch Line Mic",
      "mapUrl": "https://www.google.com/maps/place/Punch+Line+Philly/@39.9652783,-75.1377628,16z/data=!3m1!4b1!4m6!3m5!1s0x89c6c8663a5f4b3b:0xa02ad66ad7ad7450!8m2!3d39.9652742!4d-75.1351879!16s%2Fg%2F11bzx1hbkn?entry=ttu",
      "neighborhood": "Northern Liberties",
      "signupTime": "6:00",
      "showTime": "7:00",
      "signUpMethod": "Online + in person",
      "length": "3 min",
      "listMethod": "Lottery",
      "recurrenceDescription": "Variable",
      "host": "Variable",
      "isActive": true,
      "notes": "Check Punch Line's website or instagram for more details",
      "dayOfWeek": "Monday",
      "rrule": "N/A",
      "mictype": "Comedy"
    },
    {
      "name": "Sweeney's Comedy Open Mic",
      "mapUrl": "https://maps.app.goo.gl/3Go2dAoiXKY2wXTX6",
      "neighborhood": "Northeast Philly",
      "signupTime": "7:30",
      "showTime": "8:00",
      "signUpMethod": "In person",
      "length": "5-10 min",
      "listMethod": "In order",
      "recurrenceDescription": "Every 3rd Monday",
      "host": "Josh Jak",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "Monday",
      "rrule": "FREQ=MONTHLY;BYDAY=3MO",
      "mictype": "Comedy"
    },
    {
      "name": "Nut Hut Showcase and Open Mic",
      "mapUrl": "https://maps.app.goo.gl/ZLQw9uvRA3HirLtW8",
      "neighborhood": "Fishtown",
      "signupTime": "8:00",
      "showTime": "8:30",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Every other Monday",
      "host": "Alban Xhema",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "Monday",
      "rrule": "FREQ=WEEKLY;INTERVAL=2;BYDAY=MO",
      "mictype": "Comedy"
    },
    {
      "name": "JJ Mallon's",
      "mapUrl": "https://maps.app.goo.gl/pPQRkPm5VuyDinSq7",
      "neighborhood": "Northern Liberties",
      "signupTime": "8:30",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "",
      "listMethod": "",
      "recurrenceDescription": "Weekly",
      "host": "Ty Wood & Sam Wolf",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "Monday",
      "rrule": "FREQ=WEEKLY;BYDAY=MO",
      "mictype": "Comedy"
    },
    {
      "name": "The Comedy Jawn",
      "mapUrl": "https://maps.app.goo.gl/7nqk9eXu33NDhaRK6",
      "neighborhood": "Northern Liberties",
      "signupTime": "8:30",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "3-5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Vernon Keith Ruffin Jr.",
      "isActive": true,
      "notes": "insta: @thecomedyjawn",
      "dayOfWeek": "Monday",
      "rrule": "FREQ=WEEKLY;BYDAY=TU",
      "mictype": "Comedy"
    },
    {
      "name": "Helium Open Mic",
      "mapUrl": "https://maps.app.goo.gl/6CnSCfy5PUN1M6QG7",
      "neighborhood": "Rittenhouse",
      "signupTime": "6:00",
      "showTime": "8:00",
      "signUpMethod": "Online + in person",
      "length": "3 min",
      "listMethod": "Random",
      "recurrenceDescription": "Variable",
      "host": "Variable",
      "isActive": true,
      "notes": "Off during Philly's Phunniest",
      "dayOfWeek": "TUESDAY",
      "rrule": "N/A",
      "mictype": "Comedy"
    },
    {
      "name": "The Wet Mic",
      "mapUrl": "https://maps.app.goo.gl/QEuHCVqdyf95rKD28",
      "neighborhood": "Northern Liberties",
      "signupTime": "–",
      "showTime": "7:00",
      "signUpMethod": "DM day of",
      "length": "4 min",
      "listMethod": "Random",
      "recurrenceDescription": "Weekly",
      "host": "Brendann Burrough, Brian Chesky, Logan Malin, Amber Born",
      "isActive": true,
      "notes": "insta: @thewetmicphilly",
      "dayOfWeek": "TUESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=WE",
      "mictype": "Comedy"
    },
    {
      "name": "SoulJoel's",
      "mapUrl": "https://maps.app.goo.gl/3hNY3V4ovnKFKTNA8",
      "neighborhood": "Pottstown PA",
      "signupTime": "6:30",
      "showTime": "7:00",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Variable",
      "isActive": true,
      "notes": "website: www.souljoels.com",
      "dayOfWeek": "TUESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Fat Lady Mic",
      "mapUrl": "https://www.google.com/maps/place/Fat+Lady+Brewing/@40.0253143,-75.2253443,17z/data=!3m1!4b1!4m6!3m5!1s0x89c6b9cdef7275f9:0xa48c6b91c32122a9!8m2!3d40.0253102!4d-75.2227694!16s%2Fg%2F11nx3yzx04?entry=ttu",
      "neighborhood": "Manayunk",
      "signupTime": "–",
      "showTime": "7:30",
      "signUpMethod": "Online day before/of",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Jim Gillespie & Rob Stant",
      "isActive": true,
      "notes": "Sign up link posted in Philly Comedy Network facebook group the day before",
      "dayOfWeek": "TUESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=FR",
      "mictype": "Comedy"
    },
    {
      "name": "Dawson Street Pub Open Mic",
      "mapUrl": "https://maps.app.goo.gl/NdMSioXsb5kqTsAR7",
      "neighborhood": "Manayunk",
      "signupTime": "7:30",
      "showTime": "8:00",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "In order",
      "recurrenceDescription": "Every other Tuesday",
      "host": "Jesse Draham",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "TUESDAY",
      "rrule": "FREQ=WEEKLY;INTERVAL=2;BYDAY=TU",
      "mictype": "Comedy"
    },
    {
      "name": "Close Quarters Comedy",
      "mapUrl": "https://maps.app.goo.gl/HLdw5WHtYztZ1RrU7",
      "neighborhood": "Old City",
      "signupTime": "8:00",
      "showTime": "8:30",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "Random",
      "recurrenceDescription": "Weekly",
      "host": "Adam Flick & Charlie Gibson",
      "isActive": true,
      "notes": "insta: @closequarterscomedy",
      "dayOfWeek": "TUESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=WE",
      "mictype": "Comedy"
    },
    {
      "name": "2street Open Mic",
      "mapUrl": "https://maps.app.goo.gl/nXS2SbQg5Pqn5KJ6A",
      "neighborhood": "South Philly",
      "signupTime": "9:30",
      "showTime": "10:30",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "Mostly in order",
      "recurrenceDescription": "Weekly",
      "host": "Tara Hernon, Brody Martin, Christian Chomik, Andrew DiPasquale, Pete Eckenroth",
      "isActive": true,
      "notes": "2street is a great try anything, work it out kind of mic, we run late but we give everyone equal opportunity to do 5 and never cut sets short or cap the list.",
      "dayOfWeek": "TUESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=WE",
      "mictype": "Comedy"
    },
    {
      "name": "Tuned Up Open Mic",
      "mapUrl": "https://maps.app.goo.gl/QEQFJcNEc6KYUaWr8",
      "neighborhood": "Spring City PA",
      "signupTime": "6:00",
      "showTime": "6:30",
      "signUpMethod": "In person",
      "length": "5-7 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Eric Preston",
      "isActive": true,
      "notes": "Workshop mic",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=WE",
      "mictype": "Comedy"
    },
    {
      "name": "Davey's Bo-pen Mic",
      "mapUrl": "https://maps.app.goo.gl/eKJHzFGekrU5oV1K8",
      "neighborhood": "Greys Ferry",
      "signupTime": "6:30",
      "showTime": "7:00",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "",
      "recurrenceDescription": "Weekly",
      "host": "Davey Bo",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Studio 700 Open Mic",
      "mapUrl": "https://maps.app.goo.gl/XguAe9XHuQoYZfT1A",
      "neighborhood": "Northern Liberties",
      "signupTime": "7:00",
      "showTime": "7:30",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "Random",
      "recurrenceDescription": "Weekly",
      "host": "Parrish McWhorter, Sean Murphy, Claire Gill",
      "isActive": true,
      "notes": "insta: @studio700comedy",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Kings Highway Comedy",
      "mapUrl": "https://maps.app.goo.gl/ombjQXZQY9CVmK176",
      "neighborhood": "Bensalem",
      "signupTime": "7:00",
      "showTime": "7:30",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "2nd Wednesday of the month",
      "host": "Dave Collins",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=2WE",
      "mictype": "Comedy"
    },
    {
      "name": "What Is It? Comedy",
      "mapUrl": "https://maps.app.goo.gl/QQbrvrsBKUqHkQre7",
      "neighborhood": "Old City",
      "signupTime": "8:30",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Jared Winters & Sam Wolf",
      "isActive": true,
      "notes": "insta: @whatisitcomedy",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Good Vibes Open Mic",
      "mapUrl": "https://maps.app.goo.gl/bQ2xpZYDMNMJNmUC7",
      "neighborhood": "West Philly",
      "signupTime": "8:30",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "London Duran & Harley Lecroix",
      "isActive": true,
      "notes": ".50 cent wings and $5 city wides",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Bar XIII Comedy Open Mic",
      "mapUrl": "https://maps.app.goo.gl/KUe3JZLhhk717NLf7",
      "neighborhood": "Wilmington DE",
      "signupTime": "8:30",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Fenris",
      "isActive": true,
      "notes": "$5 set tapes available upon request",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Off Leash New Material Mic",
      "mapUrl": "https://maps.app.goo.gl/VCg2AG2KERnHVuH88",
      "neighborhood": "Center City",
      "signupTime": "9:00",
      "showTime": "–",
      "signUpMethod": "In person",
      "length": "3 min",
      "listMethod": "",
      "recurrenceDescription": "Weekly after showcase",
      "host": "Shane O'Connor & Liam Paris",
      "isActive": true,
      "notes": "insta: @offleashcomedy",
      "dayOfWeek": "WEDNESDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Comedy Open Mic w/ Kerri",
      "mapUrl": "https://maps.app.goo.gl/yyDBXEvwsmRSmVrX7",
      "neighborhood": "Lansdale",
      "signupTime": "6:00",
      "showTime": "7:00",
      "signUpMethod": "In person",
      "length": "< 10 min",
      "listMethod": "In order",
      "recurrenceDescription": "Last Thursday of the month",
      "host": "Kerri",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=-1TH",
      "mictype": "Comedy"
    },
    {
      "name": "Gojjo",
      "mapUrl": "https://maps.app.goo.gl/Gv1vogoB1o4c2M1f8",
      "neighborhood": "West Philly",
      "signupTime": "6:30",
      "showTime": "7:00",
      "signUpMethod": "In person or dm day of",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Weekly",
      "host": "Felix Behr",
      "isActive": true,
      "notes": "Optional 1 min of feedback; you can dm, but will be added to the list once Felix sees you",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=FR",
      "mictype": "Comedy"
    },
    {
      "name": "Lady Laughs",
      "mapUrl": "https://www.google.com/maps/place/The+Painted+Mug+Cafe/@39.9236673,-75.1751604,17z/data=!3m1!4b1!4m6!3m5!1s0x89c6c7889a56efdd:0x9ac79a9a2049746e!8m2!3d39.9236632!4d-75.1725855!16s%2Fg%2F11pl94vc1_?entry=ttu",
      "neighborhood": "South Philly",
      "signupTime": "6:30",
      "showTime": "7:00",
      "signUpMethod": "In person",
      "length": "3-5 min",
      "listMethod": "Random",
      "recurrenceDescription": "2nd Thursday bi-monthly",
      "host": "Lady Laughs Philly rotating hosts",
      "isActive": true,
      "notes": "2024 dates: June, August, Oct, Dec; Anyone is welcome to sign up/perform, order prioritizes women and queer comics; At sign up, comics sign an agreement to not use bigoted language and to tell jokes that speak to their own experiences.",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=MONTHLY;INTERVAL=2;BYDAY=2TH",
      "mictype": "Comedy"
    },
    {
      "name": "The Monthly Peel",
      "mapUrl": "https://maps.app.goo.gl/RUtVZ24QF7iqdt4e6",
      "neighborhood": "Fishtown",
      "signupTime": "6:30",
      "showTime": "7:00",
      "signUpMethod": "In person or dm day of",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "Last Thursday of the month",
      "host": "Chadwick Dravk and special guests",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=-1TH",
      "mictype": "Comedy"
    },
    {
      "name": "KIS Entertainment",
      "mapUrl": "https://maps.app.goo.gl/FZkCA6YW8Qf7zBE76",
      "neighborhood": "West Philly",
      "signupTime": "7:00",
      "showTime": "7:15",
      "signUpMethod": "DM day of",
      "length": "5 min",
      "listMethod": "In order",
      "recurrenceDescription": "1st & 3rd Thursday",
      "host": "Variable",
      "isActive": true,
      "notes": "insta: @kisentertainment",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=1TH,3TH",
      "mictype": "Comedy"
    },
    {
      "name": "Crave Laughs",
      "mapUrl": "https://maps.app.goo.gl/UJLTDUGm1kmDSrt59",
      "neighborhood": "Lawrenceville NJ",
      "signupTime": "7:15",
      "showTime": "7:30",
      "signUpMethod": "Email",
      "length": "5 min",
      "listMethod": "Random",
      "recurrenceDescription": "4th Thursday of the month",
      "host": "Tavi Nathanson",
      "isActive": true,
      "notes": "Email tavi.laughs@gmail.com to sign up; show up at 7:15",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=4TH",
      "mictype": "Comedy"
    },
    {
      "name": "Raven Lounge Comedy",
      "mapUrl": "https://maps.app.goo.gl/HY84HHvPyfEZKr7DA",
      "neighborhood": "Rittenhouse",
      "signupTime": "8:00",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "5 min",
      "listMethod": "",
      "recurrenceDescription": "Weekly",
      "host": "Paige Campbell",
      "isActive": true,
      "notes": "insta: @ravenloungecomedy",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Good Hang",
      "mapUrl": "https://maps.app.goo.gl/Hfmiwhd4PCDBgccAA",
      "neighborhood": "South Philly",
      "signupTime": "8:00",
      "showTime": "–",
      "signUpMethod": "In person",
      "length": "3-4 min",
      "listMethod": "In order",
      "recurrenceDescription": "2nd Thursday after showcase",
      "host": "Hannah Trav, Jon Deary, Anna Gallagher, Leah Frances",
      "isActive": true,
      "notes": "insta: @goodhangcomedy",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=2TH",
      "mictype": "Comedy"
    },
    {
      "name": "JJ's Mic",
      "mapUrl": "https://maps.app.goo.gl/pPQRkPm5VuyDinSq7",
      "neighborhood": "Fishtown",
      "signupTime": "9:00",
      "showTime": "9:30",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "Random",
      "recurrenceDescription": "Weekly after showcase",
      "host": "Claudia Estrada & Alban Xhema",
      "isActive": true,
      "notes": "",
      "dayOfWeek": "THURSDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=TH",
      "mictype": "Comedy"
    },
    {
      "name": "Free New Material Show",
      "mapUrl": "https://maps.app.goo.gl/BpYxPFMLmhwvKD4D7",
      "neighborhood": "Spring Garden",
      "signupTime": "10:00",
      "showTime": "10:30",
      "signUpMethod": "In person",
      "length": "3-5 min",
      "listMethod": "",
      "recurrenceDescription": "Weekly",
      "host": "Variable",
      "isActive": true,
      "notes": "insta: @nextinlinecomedy",
      "dayOfWeek": "FRIDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=SU",
      "mictype": "Comedy"
    },
    {
      "name": "The Funny Bone",
      "mapUrl": "https://maps.app.goo.gl/8yCGS6eJmiP9fv2x8",
      "neighborhood": "Manayunk",
      "signupTime": "4:30",
      "showTime": "5:00",
      "signUpMethod": "In person",
      "length": "Varies",
      "listMethod": "In order",
      "recurrenceDescription": "2nd & 4th Sunday",
      "host": "Dr. Holly",
      "isActive": true,
      "notes": "We also workshop jokes and provide feedback",
      "dayOfWeek": "SUNDAY",
      "rrule": "FREQ=MONTHLY;BYDAY=2SU,4SU",
      "mictype": "Comedy"
    },
    {
      "name": "Party Zone!",
      "mapUrl": "https://maps.app.goo.gl/VCg2AG2KERnHVuH88",
      "neighborhood": "Center City",
      "signupTime": "8:30",
      "showTime": "9:00",
      "signUpMethod": "In person",
      "length": "4 min",
      "listMethod": "Random",
      "recurrenceDescription": "Weekly",
      "host": "Campbell Gibson & Audrey Ozer",
      "isActive": true,
      "notes": "insta: @partyzonecomedymic",
      "dayOfWeek": "SUNDAY",
      "rrule": "FREQ=WEEKLY;BYDAY=SU",
      "mictype": "Comedy"
    }
   ];

export async function uploadOpenMicData() {
  const collectionRef = collection(db, "mics");

  try {
    for (const mic of openMicData) {
      await addDoc(collectionRef, mic);
    }
    console.log("Data uploaded successfully");
  } catch (e) {
    console.error("Error adding document: ", e);
  }
}
